name: "CI - automação continua"

on:
  pull_request:
    branches:
      - 'feature**'
      - 'develop'
      - 'main'

jobs:
  robot-test:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
          architecture: "x64"
      - name: Setup end Execution Robot
        continue-on-error: true
        shell: bash
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip3 install robotframework-seleniumlibrary
          robot -d tests/cadastro.robot .