name: "1 - setup automatico"

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - ready_for_review
    branches:
      - 'feature**'
      - 'develop'
      - 'main'

jobs:
  robocop:
    name: Run setup
    runs-on: itau-linux-k8s-on-demand-low
    continue-on-error: true
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
          architecture: "x64"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Setup Robot
        shell: bash
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip3 install robotframework-seleniumlibrary

      - name: Run projeto automatizado
        continue-on-error: true
        shell: bash
        run: robot -d tests/cadastro.robot .